dist: trusty
sudo: required

addons:
  chrome: stable

services:
  - mysql
  - elasticsearch

node_js:
  - "6"

before_install:
  - cp deploy/database.travis.yml config/database.yml
  - npm install
  - bundle install
  - bundle exec rake db:test:load

  # - deploy/dockerize.sh $TRAVIS_COMMIT test
  # - docker pull mysql
  # - docker pull elasticsearch:2.4.4
  # - docker run -d -e MYSQL_ROOT_PASSWORD=root --name mysql mysql
  # - docker run -d --name elastic elasticsearch:2.4.4

# install: true

script:
  - bundle exec rspec spec/
  - HEADLESS=true bundle exec cucumber features/
  # - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec rake db:drop db:setup db:test:load
  # - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec rspec spec --format=progress
  # - docker run --rm --link mysql:mysql --link elastic:elastic -e HEADLESS=true docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec cucumber features --format=progress
