dist: trusty
sudo: required

env:
  global:
    - HEADLESS=true
    - DATABASE_URL="mysql2://travis@localhost/kor_test?encoding=utf8&collation=utf8_unicode_ci"

addons:
  chrome: stable

services:
  - mysql
  - elasticsearch

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 6B05F25D762E3157
  - sudo apt-get -qq update
  - sudo apt-get install -y libav-tools imagemagick chromium-chromedriver
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.12.deb 
  - sudo dpkg -i --force-confnew elasticsearch-5.6.12.deb
  - sudo service elasticsearch restart
  - nvm install v8.12.0
  - nvm alias default v8.12.0
  - gem update --system
  - gem install bundler

install:
  - npm install
  - bundle install --jobs=3 --retry=3 --deployment
  - npm run build

script:
  - mysql -e 'CREATE DATABASE kor_test;'
  - bundle exec rake db:test:load
  - bundle exec rspec spec/ --tag ~travis:false --format=documentation
  - bundle exec cucumber features/ --format=pretty --tags "~@notravis" --no-strict --retry 3
