dist: trusty
sudo: required

env:
  global:
    - HEADLESS=true
    - DATABASE_URL="mysql2://travis@localhost/kor_test?encoding=utf8&collation=utf8_unicode_ci"

addons:
  chrome: stable

services:
  - mysql
  - elasticsearch

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libav-tools imagemagick
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.12.deb 
  - sudo dpkg -i --force-confnew elasticsearch-5.6.12.deb
  - sudo service elasticsearch restart
  - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo ln -sfn $(pwd)/chromedriver /usr/local/bin/chromedriver
  - nvm install v8.12.0
  - nvm alias default v8.12.0

install:
  - npm install
  - bundle install --jobs=3 --retry=3 --deployment
  - npm run build

script:
  - mysql -e 'CREATE DATABASE kor_test;'
  - bundle exec rake db:test:load
  - bundle exec rspec spec/ --tag ~travis:false --format=documentation
  - bundle exec cucumber features/ --format=pretty --tags "~@notravis" --no-strict
