dist: trusty
sudo: required

rvm:
  - 2.4.1

env:
  - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest

services:
  - mysql
  - elasticsearch

node_js:
  - "6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libav-tools imagemagick
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.6/elasticsearch-2.4.6.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.6.deb && sudo service elasticsearch restart
  - mysql -e 'CREATE DATABASE kor_test;'
  - cp deploy/database.travis.yml config/database.yml
  - npm install
  - npm run build
  # - bundle install
  - bundle exec rake db:test:load

  # - deploy/dockerize.sh $TRAVIS_COMMIT test
  # - docker pull mysql
  # - docker pull elasticsearch:2.4.4
  # - docker run -d -e MYSQL_ROOT_PASSWORD=root --name mysql mysql
  # - docker run -d --name elastic elasticsearch:2.4.4

# install: true

script:
  - bundle exec rspec spec/
  - bundle exec cucumber features/
  # - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec rake db:drop db:setup db:test:load
  # - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec rspec spec --format=progress
  # - docker run --rm --link mysql:mysql --link elastic:elastic -e HEADLESS=true docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec cucumber features --format=progress
