sudo: required

services:
  - docker

before_install:
  - deploy/dockerize.sh $TRAVIS_COMMIT test
  - docker pull mysql
  - docker pull elasticsearch:2.4.4
  - docker run -d -e MYSQL_ROOT_PASSWORD=root --name mysql mysql
  - docker run -d --name elastic elasticsearch:2.4.4

# install: true

script:
  - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec rake db:setup
  - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec rspec spec --format=progress
  - docker run --rm --link mysql:mysql --link elastic:elastic -e HEADLESS=true docker.coneda.net:443/kor:$TRAVIS_COMMIT bundle exec cucumber features --format=progress
